# What are Tidy Data? {#intro}

* Define tidy data
* Describe benefits of tidy data  [**covered, but needs more**]
* Examples of non-tidy --> tidy
* Examples of general data science workflows in R [**maybe covered?**]
* Intro to / Explanation of the tidyverse ecosystem
        

# Reading in Data

* External data to tibbles [explicit discussion of tibbles **missing**]
* Reading in spreadsheets (googlesheets, readxl, googledrive)
* CSV/delimited text files (readr)
* Foreign formats (haven) [**missing**]
* JSON (jsonlite)
* SQL (dbplyr)
* Web scraping (rvest)
* APIs (httr)
* Images (magick)  [details **missing**] - not sure if we should include
* Audio? (tuneR and seawave)  [details **missing**] - not sure if we should include


# Tidying Your Data

* Data wrangling (dplyr, tidyr, forcats, glue) [**`glue` missing**]
* Dates/times (lubridate)
* Strings/regex (stringr)
* tidytext example [**covered, but needs more** (I have some of this elsewhere)]
* Functional programming (purrr) [**missing**]
* Basic EDA


# Visualization

* Principles of visualization
* Types of plots
* EDA w/ggplot2
* ggplot2 fundamentals
* gganimate, ggrepel [**missing** (some basics are covered)]
* tables (knitr, kableExtra)
* multiple plots (cowplot) [**missing**]


# Prediction Modeling with Tidy Data

* recipes [**missing** (`caret` is covered briefly)]
* broom [**missing** (bascis are covered)]
* caret
* time series, forecasting (tidyverts, tsibble, fable, feasts)

