# About the Authors {-}


**Carrie Wright** is a Research Associate in the Department of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. Prior to joining the Johns Hopkins Data Science Lab, Dr. Wright was a Posdoctoral Fellow at the [Lieber Institute for Brain Development (LIBD)](https://www.libd.org/), where her research focused on uncovering genetic mechanisms in psychiatric disease through the utilization of data science tools. At LIBD, she cofounded the [LIBD rstats club](http://research.libd.org/rstatsclub/), a community designed to encourage others to learn more about R programming and statistics. Carrie can be found on Twitter at [mirnas22](https://twitter.com/mirnas22) and on GitHub under the user name [carriewright11](https://github.com/carriewright11).


**Shannon E. Ellis** is an Assistant Teaching Professor of [Cognitive Science](http://www.cogsci.ucsd.edu) at the [University of California San Deigo](https://ucsd.edu). She teaches data science to thousands of undergradates each year and is a developer of the [Cloud-Based Data Science](https://www.clouddatascience.org) Course Set on [Leanpub](https://leanpub.com/universities/set/jhu/cloud-based-data-science). Shannon can be found on Twitter at [Shannon_E_Ellis](https://twitter.com/Shannon_E_Ellis) and on GitHub under the user name [ShanEllis](https://github.com/shanellis).


**Stephanie C. Hicks** is an Assistant Professor of [Biostatistics](https://www.jhsph.edu/departments/biostatistics) at the [Johns Hopkins Bloomberg School of Public Health](https://www.jhsph.edu). She is also a faculty member of the [Johns Hopkins Data Science Lab](http://jhudatascience.org), co-host of [The Corresponding Author](https://twitter.com/CorrespondAuth) podcast and co-founder of [R-Ladies Baltimore](https://rladies-baltimore.github.io). Stephanie can be found on Twitter and GitHub under the user name [stephaniehicks](https://twitter.com/stephaniehicks).


**Roger D. Peng** is a Professor of Biostatistics at the Johns Hopkins Bloomberg School of Public Health. He is also a Co-Founder of the [Johns Hopkins Data Science Specialization](http://www.coursera.org/specialization/jhudatascience/1), which has enrolled over 5 million students, the [Johns Hopkins Executive Data Science Specialization](https://www.coursera.org/specializations/executive-data-science), the [Simply Statistics blog](http://simplystatistics.org/) where he writes about statistics and data science for the general public, and the [Not So Standard Deviations](https://soundcloud.com/nssd-podcast) podcast. Roger can be found on Twitter and GitHub under the user name [rdpeng](https://twitter.com/rdpeng).

