# What are Tidy Data? {#intro}

Course Objectives:
- Define tidy data 
- Break down conceptually how to go take data from non-tidy to tidy 
- Defend the benefits of and explain the hurdles in working with tidy data
- Deduce appropriate R package for a given data tidying task

Possible Assessments:
- MC: Provide untidy versions of small datasets -> Choose which is tidied version
- Matching: tidy data principles to examples
- MC: Give task -> choose appropriate package

# Reading in Data

Course Objectives:
- Bullet point the differences between data types
- Choose appropriate package for data reading task
- Execute reading various data types, including CSVs, spreadhseets, JSON/XML, databases, website, and APIs, into R 

Possible Assessments:
- swirl?: As for code needed to read in various data types
- MC: choose appropriate package and function
- peer - read dataset in (using datasets that will be used throughout)

# Tidying Your Data

Course Objectives:
- Use tidyverse packages to programmatically take data from non-tidy to tidy
- Summarize and interpret a dataset using skimr
- Modify string data using stringr and regular expressions
- Explain the issues faced when working with dates and times
- Demonstrate ability to work with dates and times (including timezones)
- Explain fundaments and recognize limitations of working with text data
- Devise a plan to utilize functional programming in data wrangling
- Execute basic exploratory data analysis

Possible Assessments:
- swirl: Give dataset and walk through tidying
- swirl: skimr/data summary
- swirl: stringr
- swirl: regex
- swirl: lubridate
- swirl: purrr
- swirl: tidytext
- MC: questions about working with dates and times
- MC: quesitons about descriptive statistics
- MC: quesitons about text data/analysis
- peer - tidydatasets (using datasets that will be used throughout)

# Visualization

Course Objectives:
- Define fundamental principles of visualization for plots and tables
- Identify appropriate visualization for given data
- Utilize ggplot2 to generate basic visualizations
- Iterate to improve basic visualizations using best practices using ggplot2, ggrepel, cowplot, and kableExtra
- Generate appropriate, interactive visualizations using gganimate

Possible Assessments:
- swirl: viz basics
- swirl: improve using best practices
- swirl: ggrepel
- swirl: cowplot
- swirl: kableExtra
- swirl: gganimate
- MC: questions about appropriate viz
- MC: questions assessing best practices (plots & tables)
- peer: reproduce a published visualization given the data using ggplot2 (and other packages)
- peer: visualize datasets being used throughout


# Prediction Modeling with Tidy Data

Course Objectives:TBD
Possible Assessments: TBD

* recipes [**missing** (`caret` is covered briefly)]
* broom [**missing** (bascis are covered)]
* caret
* time series, forecasting (tidyverts, tsibble, fable, feasts)
