# What are Tidy Data? {#intro}

* Define tidy data
* Describe benefits of tidy data  [**covered, but needs more**]
* Examples of non-tidy --> tidy
* Examples of general data science workflows in R [**maybe covered?**] (Data Science Lifecycle?)
* Intro to / Explanation of the tidyverse ecosystem
        

# Reading in Data

* External data to tibbles [explicit discussion of tibbles **missing**]
* Reading in spreadsheets (googlesheets, readxl, googledrive)
* CSV/delimited text files (readr)
* Foreign formats (haven) [**missing**]
* JSON (jsonlite)
* SQL (dbplyr)
* Web scraping (rvest)
* APIs (httr)
* Images (magick)  [details **missing**] - not sure if we should include
* Audio? (tuneR and seawave)  [details **missing**] - not sure if we should include


# Tidying Your Data

* Data wrangling (dplyr, tidyr, forcats, glue, janitor, skimr, naniar) [**`glue` missing**] - remove reshape2?
* Dates/times (lubridate)
* Strings/regex (stringr)
* tidytext example [**covered, but needs more** (I have some of this elsewhere)]
* Functional programming (purrr) [**missing**]
* Basic EDA


# Visualization

* Principles of visualization
* Types of plots
* EDA w/ggplot2
* ggplot2 fundamentals
* gganimate, ggrepel [**missing** (some basics are covered)]
* tables (knitr, kableExtra)
* multiple plots (cowplot) [**missing**]


# Prediction Modeling with Tidy Data

Linear modeling

* lm, glm
* broom / tidy model processing
* basic inference with linear models
* penalization (L2 ridge / L1 lasso)

Some prediction modeling concepts

* What is prediction / prediction error
* train / test sets
* evaluation metrics (mse, fpr, tpr, recall, etc.)

The parsnip / tidymodels cycle

* recipes - prepare data
* juice / bake - create datasets
* model specification
* engine
* prediction / posterior sims

Applications

* Simple linear regression
* Basic machine learning
* Some Bayesian thing (w/Stan)?



















